version: "3"

services:
  s3:
    image: zenko/cloudserver:latest
    container_name: s3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # networks:
    #   - traefik-proxy
    # labels:
    #   traefik.enable: true
    #   traefik.http.routers.s3.entryPoints: https
    #   traefik.http.services.s3.loadbalancer.server.port: 8000
    environment:
      SCALITY_ACCESS_KEY_ID: ${SCALITY_ACCESS_KEY_ID:?error}
      SCALITY_SECRET_ACCESS_KEY: ${SCALITY_SECRET_ACCESS_KEY:?error}
      # S3DATA: multiple
      S3BACKEND: file
      ENDPOINT: s3.castelnuovo.xyz
    volumes:
        - ./data:/usr/src/app/localData
        - ./metadata:/usr/src/app/localMetadata
        # - ./authdata.json:/usr/src/app/conf/authdata.json
    ports:
      - 8000:8000
      - 8900:8900

networks:
  traefik-proxy:
    driver: bridge
    external: true
